steps:
  
  - id: "Instalação do Go WebServer Google CB"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'app']
    env: ['GOPATH=.']
    
  - id: 'Executando o do Go Webserver Google CB'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','./...']
    env: ['GOPATH=.']